[package]
name = "tracing_chromium"
version = "0.1.0"
authors = ["Josh Gao <josh@jmgao.dev>"]
edition = "2018"

[dependencies]
tracing_facade = { path = "../tracing_facade", version = "0.1" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

gettid = "0.1"
time = "0.1"
